import { format, addDays } from 'date-fns';
import { generateUnsubscribeUrl } from './jwt-utils';

export interface MealPlanEmailData {
  userName: string;
  weekStartDate: string;
  userEmail: string;
  userId: string;
  meals: {
    [day: string]: {
      [mealType: string]: string | { name: string };
    };
  };
  mealSettings?: {
    enabledMealTypes: string[];
  };
}

export function generateMealPlanEmail({ userName, weekStartDate, userEmail, userId, meals, mealSettings }: MealPlanEmailData): string {
  const weekStart = new Date(weekStartDate);
  const enabledMeals = mealSettings?.enabledMealTypes || ['breakfast', 'lunch', 'dinner'];
  
  const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
  const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  
  const mealTypeLabels: { [key: string]: string } = {
    breakfast: 'Breakfast',
    morningSnack: 'Morning Snack',
    lunch: 'Lunch',
    eveningSnack: 'Evening Snack',
    dinner: 'Dinner'
  };

  const weekRange = `${format(weekStart, 'MMM d')} - ${format(addDays(weekStart, 6), 'MMM d, yyyy')}`;
  const unsubscribeUrl = generateUnsubscribeUrl(userEmail, userId);

  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Weekly Meal Plan - ${weekRange}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto; background-color: #f8f9fa; border: 1px solid #e9ecef; border-radius: 12px; padding: 12px;">
    <div style="background-color: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
        <div style="text-align: center; padding-bottom: 15px; border-bottom: 2px solid #e9ecef;">
            <h1 style="color: #2c3e50; margin: 0 0 8px 0; font-size: 28px;">🍽️ Your Weekly Meal Plan</h1>
            <p style="color: #6c757d; margin: 0 0 12px 0; font-size: 16px;">Hello ${userName}! Here's your personalized meal plan for the week.</p>
            <p style="margin: 0; font-size: 14px;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://khanakyabanau.in'}" style="color: #007bff; text-decoration: none; font-weight: 500;">🔗 Open khanakyabanau.in</a>
            </p>
        </div>
        
        <div style="background-color: #f8f9fa; padding: 20px; text-align: center;">
            <h2 style="margin: 0 0 5px 0; color: #495057; font-size: 20px;">Week of ${weekRange}</h2>
            <p style="margin: 0; color: #6c757d; font-size: 14px;">Plan your grocery shopping and meal prep with confidence!</p>
        </div>
        
        <div style="margin-bottom: 20px;">
            ${days.map((day, index) => {
              const dayMeals = meals[day] || {};
              const isLastDay = index === days.length - 1;
              return `
                <div style="margin-bottom: ${isLastDay ? '0' : ''}; ${!isLastDay ? 'border-bottom: 2px solid #e9ecef; padding-bottom: 20px;' : ''}">
                    <div style="background-color: #495057; color: white; padding: 10px 16px; font-weight: 600; font-size: 16px; margin-bottom: 12px;">${dayNames[index]}</div>
                    <div style="padding: 0 12px;">
                        ${enabledMeals.map((mealType, mealIndex) => {
                          const mealName = dayMeals[mealType] instanceof Object ? dayMeals[mealType].name : dayMeals[mealType];
                          const isLastMeal = mealIndex === enabledMeals.length - 1;
                          return `
                            <div style="padding: 8px 0; ${!isLastMeal ? 'border-bottom: 1px solid #e9ecef;' : 'padding-bottom: 16px;'}">
                                <div style="font-weight: 600; color: #495057; margin-bottom: 3px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px;">${mealTypeLabels[mealType] || mealType}</div>
                                <div style="color: #212529; font-size: 16px; ${!mealName ? 'color: #6c757d; font-style: italic;' : ''}">
                                    ${mealName || 'Not planned yet'}
                                </div>
                            </div>
                          `;
                        }).join('')}
                    </div>
                </div>
              `;
            }).join('')}
        </div>
        
        <div style="text-align: center; padding-top: 16px; border-top: 1px solid #e9ecef; color: #6c757d; font-size: 14px;">
            <p style="margin: 0 0 8px 0;">
                <strong>Happy cooking! 🧑‍🍳</strong><br>
                This meal plan was generated by your personal AI assistant.
            </p>
            <p style="margin: 0 0 12px 0;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://khanakyabanau.in'}" style="color: #007bff; text-decoration: none;">Visit your meal planner</a> 
                to make changes or generate new plans.
            </p>
            <div style="border-top: 1px solid #e9ecef; padding-top: 12px; margin-top: 12px;">
                <p style="margin: 0 0 10px 0; font-size: 12px; color: #6c757d;">
                    Don't want to receive these emails anymore?
                </p>
                <a href="${unsubscribeUrl}" style="color: #dc3545; text-decoration: none; font-size: 12px;">
                    Unsubscribe from weekly meal plans
                </a>
            </div>
        </div>
    </div>
</body>
</html>
  `;
}

export function generateMealPlanTextEmail({ userName, weekStartDate, userEmail, userId, meals, mealSettings }: MealPlanEmailData): string {
  const weekStart = new Date(weekStartDate);
  const enabledMeals = mealSettings?.enabledMealTypes || ['breakfast', 'lunch', 'dinner'];
  
  const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
  const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  
  const mealTypeLabels: { [key: string]: string } = {
    breakfast: 'Breakfast',
    morningSnack: 'Morning Snack',
    lunch: 'Lunch',
    eveningSnack: 'Evening Snack',
    dinner: 'Dinner'
  };

  const weekRange = `${format(weekStart, 'MMM d')} - ${format(addDays(weekStart, 6), 'MMM d, yyyy')}`;
  const unsubscribeUrl = generateUnsubscribeUrl(userEmail, userId);

  let text = `🍽️ Your Weekly Meal Plan\n\n`;
  text += `Hello ${userName}!\n`;
  text += `Here's your personalized meal plan for the week of ${weekRange}.\n\n`;
  text += `🔗 Open Meal Planner App: ${process.env.NEXT_PUBLIC_APP_URL || 'https://khanakyabanau.in'}\n\n`;
  text += `Plan your grocery shopping and meal prep with confidence!\n\n`;

  days.forEach((day, index) => {
    const dayMeals = meals[day] || {};
    text += `${dayNames[index]}:\n`;
    text += `${'='.repeat(dayNames[index].length)}\n`;
    
    enabledMeals.forEach(mealType => {
      const mealName = dayMeals[mealType];
      const label = mealTypeLabels[mealType] || mealType;
      text += `${label}: ${mealName || 'Not planned yet'}\n`;
    });
    
    text += '\n';
  });

  text += `Happy cooking! 🧑‍🍳\n\n`;
  text += `This meal plan was generated by your personal AI assistant.\n`;
  text += `Visit your meal planner to make changes or generate new plans.\n`;
  text += `${process.env.NEXT_PUBLIC_APP_URL || 'https://your-app.vercel.app'}\n\n`;
  text += `---\n`;
  text += `Don't want to receive these emails anymore?\n`;
  text += `Unsubscribe: ${unsubscribeUrl}\n`;

  return text;
}